//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ClientTags : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClientTags defaultInstance = ((ClientTags)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClientTags())));
        
        public static ClientTags Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>{94e48483-ebc4-44fd-a802-f8574d1d66d0}</string>
  <string>{917e7edc-c6f0-47df-b852-e680a524a379}</string>
  <string>{e9258bd2-e068-4158-8bf2-602696c6d268}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TagList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TagList"]));
            }
        }
    }
}
