//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DataObjects.EntityFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Sitecore_EntityFrameworkEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Sitecore_EntityFrameworkEntities object using the connection string found in the 'Sitecore_EntityFrameworkEntities' section of the application configuration file.
        /// </summary>
        public Sitecore_EntityFrameworkEntities() : base("name=Sitecore_EntityFrameworkEntities", "Sitecore_EntityFrameworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Sitecore_EntityFrameworkEntities object.
        /// </summary>
        public Sitecore_EntityFrameworkEntities(string connectionString) : base(connectionString, "Sitecore_EntityFrameworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Sitecore_EntityFrameworkEntities object.
        /// </summary>
        public Sitecore_EntityFrameworkEntities(EntityConnection connection) : base(connection, "Sitecore_EntityFrameworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sitecore_EntityFrameworkModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentID">Initial value of the commentID property.</param>
        /// <param name="articleID">Initial value of the articleID property.</param>
        /// <param name="comment1">Initial value of the comment1 property.</param>
        public static Comment CreateComment(global::System.Int32 commentID, global::System.Guid articleID, global::System.String comment1)
        {
            Comment comment = new Comment();
            comment.commentID = commentID;
            comment.articleID = articleID;
            comment.comment1 = comment1;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 commentID
        {
            get
            {
                return _commentID;
            }
            set
            {
                if (_commentID != value)
                {
                    OncommentIDChanging(value);
                    ReportPropertyChanging("commentID");
                    _commentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("commentID");
                    OncommentIDChanged();
                }
            }
        }
        private global::System.Int32 _commentID;
        partial void OncommentIDChanging(global::System.Int32 value);
        partial void OncommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid articleID
        {
            get
            {
                return _articleID;
            }
            set
            {
                OnarticleIDChanging(value);
                ReportPropertyChanging("articleID");
                _articleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleID");
                OnarticleIDChanged();
            }
        }
        private global::System.Guid _articleID;
        partial void OnarticleIDChanging(global::System.Guid value);
        partial void OnarticleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comment1
        {
            get
            {
                return _comment1;
            }
            set
            {
                Oncomment1Changing(value);
                ReportPropertyChanging("comment1");
                _comment1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comment1");
                Oncomment1Changed();
            }
        }
        private global::System.String _comment1;
        partial void Oncomment1Changing(global::System.String value);
        partial void Oncomment1Changed();

        #endregion
    
    }

    #endregion
    
}
